import "../styles/globals.css";
import { SessionProvider } from "next-auth/react";
import Navbar from "../components/Navbar";
import Head from "next/head";

function MyApp({ session, Component, pageProps }) {
	return (
		<SessionProvider session={session}>
			<Head>
				<title>Twitch</title>
				<meta name="description" content="Generated by create next app" />
				<link
					rel="icon"
					href="https://twitch-nextjs-tailwind.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.ff04bf83.png&w=96&q=75"
				/>
			</Head>
			<Navbar />
			<Component {...pageProps} />
		</SessionProvider>
	);
}

export default MyApp;
